# Generated by Django 2.0.4 on 2018-08-01 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('description', models.TextField(default='description text')),
                ('available', models.BooleanField(default=True)),
                ('Single_Bed', models.BooleanField(default=True)),
                ('Double_Bed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('NumOfAdults', models.IntegerField()),
                ('NumOfChildren', models.IntegerField()),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=100)),
                ('Address1', models.CharField(max_length=1000)),
                ('Address2', models.CharField(max_length=1000)),
                ('State', models.CharField(max_length=1000)),
                ('ZipCode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
