# Generated by Django 2.0.4 on 2018-08-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0002_auto_20180825_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
