# Generated by Django 2.0.4 on 2018-08-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0008_remove_userprofile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelReservation',
        ),
    ]
