# Generated by Django 2.0.4 on 2018-08-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0009_delete_hotelreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
    ]
