# Generated by Django 2.0.4 on 2018-09-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0010_auto_20180830_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
