# Generated by Django 2.0.4 on 2018-09-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HotelReservation', '0011_auto_20180901_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(default='', max_length=100)),
                ('roomtype', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
