# Generated by Django 2.0.4 on 2018-09-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0013_auto_20180901_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotellist',
            old_name='hotelname',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='hotellist',
            old_name='roomtype',
            new_name='room_type',
        ),
    ]
