# Generated by Django 2.0.4 on 2018-09-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0016_auto_20180901_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellist',
            name='double_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='max_number_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='single_bed',
            field=models.IntegerField(default=0),
        ),
    ]
