# Generated by Django 2.0.4 on 2018-09-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0018_hotellist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellist',
            name='image',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
    ]
