# Generated by Django 2.0.4 on 2018-09-07 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0022_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_in',
            field=models.DateField(default=datetime.date(2018, 9, 7)),
        ),
    ]
