# Generated by Django 2.0.4 on 2018-09-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0027_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
