# Generated by Django 2.0.4 on 2018-09-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0029_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='BedOption',
        ),
        migrations.AddField(
            model_name='room',
            name='Bed_Option',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='RoomType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='TotalRooms',
            field=models.CharField(default='', max_length=255),
        ),
    ]
