# Generated by Django 2.0.4 on 2018-09-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0030_auto_20180908_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
    ]
