# Generated by Django 2.0.4 on 2018-09-11 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelReservation', '0032_best_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Best_Choice',
            new_name='BestChoice',
        ),
    ]
