# Generated by Django 2.0.4 on 2018-09-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0033_auto_20180911_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
