# Generated by Django 2.0.4 on 2018-09-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0034_auto_20180911_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out',
        ),
    ]
