# Generated by Django 2.0.4 on 2018-09-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0037_remove_hotellist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellist',
            name='double_bed',
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='single_bed',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Bed_Option',
        ),
        migrations.RemoveField(
            model_name='room',
            name='TotalRooms',
        ),
    ]
