# Generated by Django 2.0.4 on 2018-09-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0039_auto_20180912_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotellist',
            options={'ordering': ('hotel_name',), 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AddField(
            model_name='hotellist',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='City',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='Country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='Telephone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='double_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='image',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='max_number_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='single_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='Capacity',
            field=models.IntegerField(default=0),
        ),
    ]
