# Generated by Django 2.0.4 on 2018-09-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0040_auto_20180913_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotellist',
            options={'verbose_name_plural': 'Hotels'},
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='double_bed',
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='single_bed',
        ),
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
