# Generated by Django 2.0.4 on 2018-09-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0042_auto_20180913_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotellist',
            options={'verbose_name_plural': 'Hotels'},
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='City',
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='Telephone',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('Single_Bed', 'Single'), ('Double_bed', 'Double')], default='', max_length=100),
        ),
    ]
