# Generated by Django 2.0.4 on 2018-09-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelReservation', '0043_auto_20180913_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotellist',
            options={'ordering': ('hotel_name',), 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AddField(
            model_name='hotellist',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='telephone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='zip_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='TotalRooms',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
