# Generated by Django 2.0.4 on 2018-09-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0044_auto_20180914_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellist',
            name='user',
        ),
    ]
