# Generated by Django 2.0.4 on 2018-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0046_auto_20180914_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellist',
            name='telephone',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
