# Generated by Django 2.0.4 on 2018-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0048_auto_20180914_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Bed_Option',
            field=models.CharField(default='', max_length=255),
        ),
    ]
