# Generated by Django 2.0.4 on 2018-09-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0049_room_bed_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellist',
            name='telephone',
        ),
    ]
