# Generated by Django 2.0.4 on 2018-09-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0052_room_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
