# Generated by Django 2.0.4 on 2018-09-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0053_auto_20180915_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_detail',
            field=models.TextField(default='', max_length=255),
        ),
    ]
