# Generated by Django 2.0.4 on 2018-10-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0057_auto_20181004_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_in',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_out',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
