# Generated by Django 2.0.4 on 2018-10-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0062_auto_20181006_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellist',
            name='latitude',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='longitude',
            field=models.CharField(default='', max_length=255),
        ),
    ]
