# Generated by Django 2.0.4 on 2018-10-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0063_auto_20181011_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellist',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='hotellist',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
