# Generated by Django 2.0.4 on 2018-10-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0064_auto_20181011_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='max_number_of_guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_days',
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
