# Generated by Django 2.0.4 on 2018-10-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0065_auto_20181013_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
