# Generated by Django 2.0.4 on 2018-10-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0066_auto_20181013_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Reservation'},
        ),
    ]
