# Generated by Django 2.0.4 on 2018-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0069_auto_20181015_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('roles', models.CharField(default='', max_length=255)),
                ('image1', models.FileField(blank=True, upload_to='post_img')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='longitude',
        ),
    ]
