# Generated by Django 2.0.4 on 2018-10-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0070_auto_20181019_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoforteam',
            name='roles2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
