# Generated by Django 2.0.4 on 2018-10-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0072_auto_20181020_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellist',
            name='max_number_of_guests',
        ),
    ]
