# Generated by Django 2.0.4 on 2018-10-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0073_remove_hotellist_max_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Bed_Option',
        ),
        migrations.AddField(
            model_name='room',
            name='Bed_Option1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='Bed_Option2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='Bed_Option3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='Bed_Option4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
