# Generated by Django 2.0.4 on 2018-10-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0075_auto_20181028_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='priorty',
            field=models.CharField(default='', max_length=255),
        ),
    ]
