# Generated by Django 2.0.4 on 2018-11-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0077_auto_20181103_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
