# Generated by Django 2.0.4 on 2018-11-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0078_room_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stored_pts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='reward_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
