# Generated by Django 2.0.4 on 2018-11-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0079_auto_20181105_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_reward_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
