# Generated by Django 2.0.4 on 2018-11-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0081_cardnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardnumber',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='room',
            name='image5',
            field=models.FileField(blank=True, upload_to='post_img'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.DeleteModel(
            name='CardNumber',
        ),
    ]
