# Generated by Django 2.0.4 on 2018-11-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0082_auto_20181124_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='switch1',
            field=models.BooleanField(default=True),
        ),
    ]
