# Generated by Django 2.0.4 on 2018-11-26 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelReservation', '0084_remove_reservation_switch1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationByPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000)),
                ('stored_pts', models.IntegerField(blank=True, default=0)),
                ('hotel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelReservation.HotelList')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelReservation.Room')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ReservationByPoint',
            },
        ),
    ]
