# Generated by Django 2.0.4 on 2018-11-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0085_reservationbypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationbypoint',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reservationbypoint',
            name='room',
        ),
        migrations.RemoveField(
            model_name='reservationbypoint',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReservationByPoint',
        ),
    ]
