# Generated by Django 2.0.4 on 2018-11-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0086_auto_20181126_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotellist',
            options={'verbose_name_plural': 'Hotels'},
        ),
    ]
